version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: ./python-backend
    container_name: python_app
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  

  react:
    build: ./login-app
    container_name: react_app
    ports:
      - "3000:3000"
    depends_on:
      - app
      

volumes:
  mongo_data:
