version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  
  backend:
    build:
      context: ./backend
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mydatabase
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
